### ISSUE TITLE
runtime: program exceeds 10000-thread limit

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#24]
Threads seem to be piling up on my kube-router pods and it is eventually killed and restarted.

```
I0607 14:14:54.708042       1 network_services_controller.go:407] ipvs service 10.3.0.15:tcp:2379 already exists so returning
I0607 14:14:54.885319       1 network_services_controller.go:448] ipvs destination 10.10.2.1:2379 already exists in the ipvs service 10.3.0.15:tcp:2379 so not adding destination
I0607 14:14:55.074909       1 network_services_controller.go:448] ipvs destination 10.10.2.2:2379 already exists in the ipvs service 10.3.0.15:tcp:2379 so not adding destination
I0607 14:14:55.249060       1 network_services_controller.go:448] ipvs destination 10.10.2.3:2379 already exists in the ipvs service 10.3.0.15:tcp:2379 so not adding destination
I0607 14:14:55.341417       1 network_policy_controller.go:94] Performing periodic syn of the iptables to reflect network policies
I0607 14:14:55.342273       1 network_services_controller.go:103] Performing periodic syn of the ipvs services and server to reflect desired state of kubernetes services and endpoints
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion

runtime stack:
runtime.throw(0x182a6f1, 0x11)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.checkmcount()
        /usr/local/go/src/runtime/proc.go:486 +0xa4
runtime.mcommoninit(0xc44146bc00)
        /usr/local/go/src/runtime/proc.go:506 +0xd5
runtime.allocm(0xc42001f500, 0x190e5c0, 0xc400000001)
        /usr/local/go/src/runtime/proc.go:1286 +0x9b
runtime.newm(0x190e5c0, 0xc42001f500)
        /usr/local/go/src/runtime/proc.go:1555 +0x39
runtime.startm(0xc42001f500, 0x100000001)
        /usr/local/go/src/runtime/proc.go:1642 +0x181
runtime.wakep()
        /usr/local/go/src/runtime/proc.go:1723 +0x57
runtime.resetspinning()
        /usr/local/go/src/runtime/proc.go:2039 +0x8b
runtime.schedule()
        /usr/local/go/src/runtime/proc.go:2127 +0x136
runtime.mstart1()
        /usr/local/go/src/runtime/proc.go:1136 +0xd8
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1096 +0x64

goroutine 1 [chan receive, 27 minutes]:
github.com/cloudnativelabs/kube-router/app.(*KubeRouter).Run(0xc420402560, 0xc420402560, 0x0)
        /home/kube/go/src/github.com/cloudnativelabs/kube-router/app/server.go:152 +0x228
main.main()
        /home/kube/go/src/github.com/cloudnativelabs/kube-router/kube-router.go:37 +0x13c

goroutine 17 [syscall, 27 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall, 27 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive]:
github.com/cloudnativelabs/kube-router/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x246f740)
        /home/kube/go/src/github.com/cloudnativelabs/kube-router/vendor/github.com/golang/glog/glog.go:879 +0x7a
created by github.com/cloudnativelabs/kube-router/vendor/github.com/golang/glog.init.1
        /home/kube/go/src/github.com/cloudnativelabs/kube-router/vendor/github.com/golang/glog/glog.go:410 +0x21d
```

I've attached [kube-router.log.gz](https://github.com/cloudnativelabs/kube-router/files/1058318/kube-router.log.gz) which is the full log the snippet above came from.

On one of the nodes I can see the threads increasing slowly this way:
```
core@node1 ~ $ ps aux|grep kube-router
root     1834843  8.9  0.2 26928172 242768 ?     Ssl  14:14   0:31 /kube-router --run-router=true --run-firewall=true --run-service-proxy=true --cluster-cidr=10.2.0.0/16 --advertise-cluster-ip --cluster-asn=64512 --peer-asn=64512 --peer-router=10.10.10.33 --kubeconfig=/etc/kubernetes/kubeconfig
core     1839688  0.0  0.0   6736   936 pts/0    S+   14:20   0:00 grep --colour=auto kube-router
core@node1 ~ $ ps huH p 1834843|wc -l
2365
core@node1 ~ $ ps huH p 1834843|wc -l
2367
core@node1 ~ $ ps huH p 1834843|wc -l
2371
core@node1 ~ $ ps huH p 1834843|wc -l
2388
```

**Comment by murali-reddy** [comment]
Thank @bzub interesting bug. it turns out ipvslib that kube-router is using, has New() methods to create handle. Kube-router was creating handle for every interaction with ipvslib. Have changed the logic to reuse handle

Fixed by 4b3d1a3
