### ISSUE TITLE
panic on invalid net.beta.kubernetes.io/network-policy annotation

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#33]
I set the `net.beta.kubernetes.io/network-policy` annotation to an invalid (json) value:
```
kubectl annotate ns test "net.beta.kubernetes.io/network-policy={\"ingress\": {\"isolation\": \"DefaultDeny\"}}"- --overwrite
```

This caused kube-router to panic and crashloop, but only on the nodes that had pods in the namespace the policy was applied to.  Fixing the json in the annotation cleared things up.

I think I've found an unhandled Error that will lead me to a fix.  I'll submit a PR soon if I find it.

Log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4eec82]

goroutine 205 [running]:
panic(0x1645840, 0xc420018050)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cloudnativelabs/kube-router/app/controllers.(*NetworkPolicyController).syncPodFirewallChains(0xc42027a100, 0xc42089e7e0, 0x0, 0x0)
        /home/kube/go/src/github.com/cloudnativelabs/kube-router/app/controllers/network_policy_controller.go:323 +0x112
github.com/cloudnativelabs/kube-router/app/controllers.(*NetworkPolicyController).Sync(0xc42027a100)
        /home/kube/go/src/github.com/cloudnativelabs/kube-router/app/controllers/network_policy_controller.go:160 +0x2ac
github.com/cloudnativelabs/kube-router/app/controllers.(*NetworkPolicyController).OnPodUpdate(0xc42027a100, 0xc4203981f0)
        /home/kube/go/src/github.com/cloudnativelabs/kube-router/app/controllers/network_policy_controller.go:112 +0x17a
github.com/cloudnativelabs/kube-router/app/watchers.(*podWatcher).RegisterHandler.func1(0x1540e00, 0xc4203981f0)
        /home/kube/go/src/github.com/cloudnativelabs/kube-router/app/watchers/pods_watcher.go:65 +0x4a
github.com/cloudnativelabs/kube-router/utils.ListenerFunc.OnUpdate(0xc42066b800, 0x1540e00, 0xc4203981f0)
        /home/kube/go/src/github.com/cloudnativelabs/kube-router/utils/utils.go:14 +0x3a
created by github.com/cloudnativelabs/kube-router/utils.(*Broadcaster).Notify
        /home/kube/go/src/github.com/cloudnativelabs/kube-router/utils/utils.go:37 +0xa3
```

**Comment by bzub** [comment]
If I check the [error](https://github.com/cloudnativelabs/kube-router/blob/master/app/controllers/network_policy_controller.go#L322) here I am able to avoid the panic.  pod.status.hostIP is "" empty string sometimes causing this panic.  I know that hostIP can be empty while a pod is not yet scheduled to a node yet, but that doesn't seem like the root cause of the bug.

I expect that there's an error not being handled when [calling json.Unmarshal](https://github.com/cloudnativelabs/kube-router/blob/master/app/controllers/network_policy_controller.go#L623) which is more at the center of the bug.
