### ISSUE TITLE
kube-router start failed

### ISSUE THREAD

**Issue by ckeyer** [cloudnativelabs/kube-router#396]
```
kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
```
```
I0413 08:55:24.415474       1 server.go:182] Running /usr/local/bin/kube-router version v0.2.0-beta.1, built on 2018-04-12, go1.8.7
I0413 08:55:24.417965       1 health_controller.go:127] Starting health controller
E0413 08:55:29.418108       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:29.418143       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:29.918119       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:29.918149       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:30.418134       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:30.418165       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:30.918136       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:30.918165       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:31.418152       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:31.418182       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:31.918090       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:31.918115       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:32.418109       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:32.418137       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:32.918057       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:32.918089       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:33.418090       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:33.418118       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:33.918145       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:33.918176       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:34.418150       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:34.418179       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:34.918032       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:34.918057       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:35.418050       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:35.418079       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:35.918140       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:35.918174       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:36.418153       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:36.418179       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:36.918112       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:36.918140       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:37.418095       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:37.418122       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:37.918121       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:37.918151       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:38.418077       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:38.418106       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:38.918184       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:38.918215       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:39.418053       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:39.418077       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:39.918038       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:39.918063       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:40.418065       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:40.418099       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:40.918037       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:40.918075       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:41.418043       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:41.418069       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:41.918033       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:41.918060       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:42.418090       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:42.418120       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:42.918092       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:42.918124       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:43.418116       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:43.418146       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:43.918120       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:43.918148       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:44.418147       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:44.418177       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:44.918048       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:44.918072       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:45.418058       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:45.418085       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:45.918149       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:45.918178       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:46.418129       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:46.418165       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:46.918121       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:46.918150       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:47.418074       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:47.418102       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:47.918156       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:47.918190       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:48.418055       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:48.418090       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:48.918215       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:48.918261       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:49.418046       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:49.418078       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:49.918156       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:49.918184       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:50.418050       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:50.418085       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:50.918195       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:50.918248       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:51.418057       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:51.418091       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:51.918105       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:51.918139       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:52.418198       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:52.418238       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:52.918179       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:52.918210       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:53.418071       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:53.418098       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:53.918175       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:53.918200       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:54.418043       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:54.418071       1 health_controller.go:100] Network Routing Controller heartbeat missed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14b8f12]

goroutine 1 [running]:
github.com/cloudnativelabs/kube-router/app/controllers.NewNetworkPolicyController(0x2630500, 0xc420444d00, 0xc42029c7e0, 0x262a1c0, 0xc420172cf0, 0x262a1c0, 0xc420172ea0, 0x262a1c0, 0xc420172e10, 0x15, ...)
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/app/controllers/network_policy_controller.go:1474 +0xf2
github.com/cloudnativelabs/kube-router/app.(*KubeRouter).Run(0xc4202ecd80, 0x0, 0x0)
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/app/server.go:123 +0xcfa
main.Main(0x2601640, 0x0)
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/kube-router.go:66 +0x20d
main.main()
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/kube-router.go:17 +0x26

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.1-beta.0.15+027058c19b8fde-dirty", GitCommit:"027058c19b8fde1a8df247fb658b0a05bde9bd8b", GitTreeState:"dirty", BuildDate:"2018-01-05T06:23:07Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux gaea188 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ckeyer** [comment]
https://github.com/kubernetes/kubernetes/issues/62527#issuecomment-381071678

**Comment by murali-reddy** [comment]
@ckeyet could you please try `v0.2.0-beta.2` image which is the latest?

**Comment by xanonid** [comment]
With v0.2.0-beta.2, I get also repeated "Network Policy Controller heartbeat missed" messages (often for minutes). If the health point is used by kubernetes, the kube-router pods are restarted periodically. This seems to be a regression, since with v0.1.0 everything works fine.
I have not (yet?) seen a panic/SIGSEGV with v0.2.0-beta.2 and v0.2.0-beta.1.

**Comment by murali-reddy** [comment]
@ckeyer Can you check if the kube-proxy is setup properly? Manifest you deployed uses kube-proxy for service proxy. from the logs it appears that kube-router pod is not able to access the API server.

**Comment by mafzst** [comment]
I encounter a similar problem on `v0.2.0-beta.4`

On my side it's `NetworkService` which misse heartbeat. Here is my container log:

```
I0505 21:00:25.225333       1 kube-router.go:186] Running /usr/local/bin/kube-router version v0.2.0-beta.4, built on 2018-04-23T19:15:53+0000, go1.8.7
I0505 21:00:25.235460       1 health_controller.go:127] Starting health controller
I0505 21:00:25.979007       1 network_policy_controller.go:125] Starting network policy controller
time="2018-05-05T21:00:26Z" level=warning msg="Running modprobe ip_vs failed with message: `modprobe: module ip_vs not found in modules.dep`, error: exit status 1"
I0505 21:00:26.072914       1 network_services_controller.go:221] Starting network services controller
I0505 21:00:26.291757       1 network_routes_controller.go:206] Starting network route controller
I0505 21:00:26.312515       1 network_routes_controller.go:620] Could not find BGP peer info for the node in the node annotations so skipping configuring peer.
time="2018-05-05T21:00:26Z" level=info msg="Add a peer configuration for:10.10.203.145" Topic=Peer
time="2018-05-05T21:00:26Z" level=info msg="Add a peer configuration for:163.172.212.48" Topic=Peer
E0505 21:00:30.235502       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:30.735596       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:31.235548       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:31.735536       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:32.235489       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:32.735493       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:33.235547       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:33.735609       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:34.235493       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:34.735606       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:35.235533       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:35.735494       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:36.235495       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:36.735507       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:37.235520       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:37.735574       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:38.235628       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:38.735682       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:39.235684       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:39.735589       1 health_controller.go:107] NetworkService Controller heartbeat missed
E0505 21:00:40.235627       1 health_controller.go:107] NetworkService Controller heartbeat missed
I0505 21:00:40.595320       1 kube-router.go:173] Shutting down the controllers
I0505 21:00:40.595568       1 health_controller.go:154] Shutting down health controller
E0505 21:00:40.595673       1 health_controller.go:138] Health controller error: http: Server closed
I0505 21:00:40.595802       1 network_routes_controller.go:276] Shutting down network routes controller
I0505 21:00:40.595868       1 network_policy_controller.go:146] Shutting down network policies controller
```

Note: On another node all is fine. The two machines are the same

**Comment by murali-reddy** [comment]
@mafzst So there is error `Running modprobe ip_vs failed with message: modprobe: module ip_vs not found in modules.dep` which is result of docker lib network library performing`modprobe -va ip_vs` to load IPVS kernel module. Looks like there was issue loading the module. 

Perhaps related to https://github.com/kubernetes/kubernetes/issues/60869. Could you let me know what version of Kernel and distro you are using?

@xanonid are you still seeing issues with hearbeat getting missed? If you so can you check any errors in the logs and share it please.

**Comment by mafzst** [comment]
@murali-reddy 
Here some kernel/distro info:
```
root@worker-par-1:~# uname -a
Linux worker-par-1 4.10.8-docker-1 #1 SMP Tue Apr 4 16:18:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@worker-par-1:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

**Comment by murali-reddy** [comment]
@mafzst Can you quickly try [pod toolbox](https://www.kube-router.io/docs/pod-toolbox/), and see you have ipvs configured?

Lets open a different issue.

**Comment by xanonid** [comment]
@murali-reddy I do not see any missed heartbeats with v0.2.0-beta.4 (or more exactly, I see only missed heartbeats during the first 10s after startup). If v0.2.0-beta.5 could be released soon, I would be able to perform more testing.

Sidenode: Meanwhile, I experienced problems with v0.1.0 due to missed heartbeats & failing health checks when the cluster and pods are notably rescaled. These seem to be fixed with v0.2.0-beta.4.

**Comment by murali-reddy** [comment]
@xanonid thanks for sharing your observations. We will release `v0.2.0-beta.5` in a day or so. Let me also check possible cases where kube-router does not respond the health checks.

**Comment by murali-reddy** [comment]
@xanonid New release [v0.2.0-beta.5](https://github.com/cloudnativelabs/kube-router/releases/tag/v0.2.0-beta.5) is out please try and see if you see any issues with kube-router not responding to health checks.
