### ISSUE TITLE
Running virtual-kubelet/fargate causes kube-router to crash

### ISSUE THREAD

**Issue by jpds** [cloudnativelabs/kube-router#468]
Running the virtual-kubelet[1] in my kops-provisioned AWS Kubernetes cluster with Fargate[2] causes my kube-router pods to immediately crash with:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13bec15]

goroutine 512 [running]:
github.com/cloudnativelabs/kube-router/vendor/github.com/osrg/gobgp/table.(*NeighborSet).Name(0x0, 0xc42098b770, 0x1)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/osrg/gobgp/table/policy.go:543 +0x5
github.com/cloudnativelabs/kube-router/vendor/github.com/osrg/gobgp/table.(*RoutingPolicy).ReplaceDefinedSet(0xc420733ac0, 0x26f5e20, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/osrg/gobgp/table/policy.go:3289 +0x11b
github.com/cloudnativelabs/kube-router/vendor/github.com/osrg/gobgp/server.(*BgpServer).ReplaceDefinedSet.func1(0x5, 0x5)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/osrg/gobgp/server/server.go:2206 +0x43
github.com/cloudnativelabs/kube-router/vendor/github.com/osrg/gobgp/server.(*BgpServer).handleMGMTOp(0xc420d3e000, 0xc420755700)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/osrg/gobgp/server/server.go:168 +0x36
github.com/cloudnativelabs/kube-router/vendor/github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc420d3e000)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/osrg/gobgp/server/server.go:300 +0x398
created by github.com/cloudnativelabs/kube-router/pkg/controllers/routing.(*NetworkRoutingController).startBgpServer
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/routing/network_routes_controller.go:614 +0x246
```

I also saw from other logs:

```
E0615 11:23:42.759633       1 network_routes_controller.go:110] Failed initial ipset setup: Failed to sync Node Addresses ipset: ipset v6.34: Syntax error: cannot parse <nil>: resolving to IPv4 address failed
I0615 11:23:42.907558       1 bgp_peers.go:287] Received node <nil> removed update from watch API, so remove node from peer
```

[1]: https://github.com/virtual-kubelet/virtual-kubelet
[2]: https://github.com/virtual-kubelet/virtual-kubelet/tree/master/providers/aws

**Comment by aauren** [comment]
Closing as stale
