### ISSUE TITLE
SIGSEGV - Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by moomzni** [cloudnativelabs/kube-router#531]
We've recently experienced this error which left our Kuberouter daemonset running with no available pods - we had to remove the DS and re-create to resolve the issue as kubelet didn't attempt to recover the service (which was strange).

We're not doing any fancy with Kube-router other than network policies.

Stacktrace below:
```
kube-router I0905 16:47:50.756113       1 kube-router.go:207] Running /usr/local/bin/kube-router version v0.2.0, built on 2018-09-01T05:50:43+0000, go1.8.7
kube-router I0905 16:47:53.355232       1 network_policy_controller.go:126] Starting network policy controller
kube-router E0905 16:49:14.656116       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
kube-router /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
kube-router /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
kube-router /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
kube-router /home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/asm_amd64.s:514
kube-router /home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/panic.go:489
kube-router /home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/panic.go:63
kube-router /home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/signal_unix.go:290
kube-router /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go:95
kube-router /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1103
kube-router /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:221
kube-router /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:181
kube-router /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1468
kube-router /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:195
kube-router <autogenerated>:57
kube-router /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:542
kube-router /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383
kube-router /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
kube-router /home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/asm_amd64.s:2197
kube-router panic: runtime error: invalid memory address or nil pointer dereference [recovered]
kube-router   panic: runtime error: invalid memory address or nil pointer dereference
kube-router [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x98cd62]
kube-router
kube-router goroutine 32 [running]:
kube-router github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
kube-router   /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
kube-router panic(0x17de7e0, 0x273e4e0)
kube-router   /home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/panic.go:489 +0x2cf
kube-router github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/intstr.(*IntOrString).String(0x0, 0x0, 0x0)
kube-router   /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go:95 +0x22
kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).buildNetworkPoliciesInfo(0xc4206304d0, 0x1a7a37a, 0x2a, 0xc42063dda0)
kube-router   /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1103 +0x17a0
kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).Sync(0xc4206304d0, 0x0, 0x0)
kube-router   /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:221 +0x22b
kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).OnNetworkPolicyUpdate(0xc4206304d0, 0x1a22940, 0xc4206d8000)
kube-router   /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:181 +0x165
kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).newNetworkPolicyEventHandler.func1(0x1a22940, 0xc4206d8000)
kube-router   /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1468 +0x3e
kube-router github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc4201582d0, 0xc4201582e0, 0xc4201582f0, 0x1a22940, 0xc4206d8000)
kube-router   /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:195 +0x49
kube-router github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc42040a860, 0x1a22940, 0xc4206d8000)
kube-router   <autogenerated>:57 +0x73
kube-router github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc42031e910)
kube-router   /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:542 +0x287
kube-router github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.(*processorListener).(github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.run)-fm()
kube-router   /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383 +0x2a
kube-router github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc420157aa0, 0xc420228670)
kube-router   /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
kube-router created by github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
kube-router   /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x62
```

Environment details:
We're running on AKS v1.10.5
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by moomzni** [comment]
It appears this is the NetworkPolicy that was breaking things; this policy (obfuscated) basically allows all pods within a namespace to hit another pod on all ports (or it should). 

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-https-ingress-within-namespace
  namespace: testnamespace
spec:
  podSelector:
    matchLabels:
      app: nodelabel
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: testnamespace
    ports:
    - {}
```

**Comment by murali-reddy** [comment]
@moomzni thanks for reporting this issue. Is `nil pointer reference` occurring every time `kube-router` starts? Or is it just occurred one time?

**Comment by murali-reddy** [comment]
Ok thanks for repro steps. I will see if it reproduces to me.

**Comment by danboucher78** [comment]
Experiencing similar issue
```
E1030 20:56:24.670885       1 runtime.go:66] Observed a panic: invalid memory address or nil pointer dereference (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.10.4.linux.amd64/src/runtime/asm_amd64.s:573
/home/travis/.gimme/versions/go1.10.4.linux.amd64/src/runtime/panic.go:502
/home/travis/.gimme/versions/go1.10.4.linux.amd64/src/runtime/panic.go:63
/home/travis/.gimme/versions/go1.10.4.linux.amd64/src/runtime/signal_unix.go:388
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go:95
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1125
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:225
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:185
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1521
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:202
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:540
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/home/travis/.gimme/versions/go1.10.4.linux.amd64/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x91b6c2]

goroutine 118 [running]:
github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x1686860, 0x264ad70)
	/home/travis/.gimme/versions/go1.10.4.linux.amd64/src/runtime/panic.go:502 +0x229
github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/intstr.(*IntOrString).String(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go:95 +0x22
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).buildNetworkPoliciesInfo(0xc420770160, 0x192dae7, 0x2a, 0xc420afed70)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1125 +0xac0
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).Sync(0xc420770160, 0x0, 0x0)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:225 +0x267
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).OnNetworkPolicyUpdate(0xc420770160, 0x18da3e0, 0xc420812780)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:185 +0x146
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).newNetworkPolicyEventHandler.func2(0x18da3e0, 0xc420812900, 0x18da3e0, 0xc420812780)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1521 +0x3e
github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(0xc4207ce650, 0xc4207ce660, 0xc4207ce670, 0x18da3e0, 0xc420812900, 0x18da3e0, 0xc420812780)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:202 +0x5d
github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc420502a50)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:540 +0x1b7
github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.(*processorListener).(github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.run)-fm()
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383 +0x2a
github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc420451560, 0xc4207cea60)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```
Versions details
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aauren** [comment]
Could not reproduce in a vanilla environment with an adapted version of the above policy, this was likely a transient issue.
