### ISSUE TITLE
crash: kube-router assumes a port is always present in network policies

### ISSUE THREAD

**Issue by adamtulinius** [cloudnativelabs/kube-router#642]
Kube router (0.2.3 and newer, at least) will crash when encountering the following _valid_ network policy:
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: allow-oracle
  namespace: user-atu
spec:
  egress:
  - ports:
    - protocol: TCP
  ingress:
  - ports:
    - protocol: TCP
  podSelector:
    matchLabels:
      app: toolbox
  policyTypes:
  - Egress
  - Ingress
```

with the following error:
```
Jan 20 23:24:29 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]: I0120 23:24:29.413044   29765 kube-router.go:207] Running /nix/store/9i4symcsky9iypfvlqs2zi300czc6ida-kube-router-0.2.3-bin/bin/kube-router version 0.2.3, built on Nix, go1.11.4
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]: I0120 23:24:30.021251   29765 metrics_controller.go:128] Starting metrics controller
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]: I0120 23:24:30.055622   29765 network_policy_controller.go:130] Starting network policy controller
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x954182]
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]: goroutine 163 [running]:
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]: github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/intstr.(*IntOrString).String(0x0, 0x0, 0x0)
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]:         /build/go/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go:95 +0x22
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]: github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).buildNetworkPoliciesInfo(0xc000786210, 0x1980e99, 0x2a, 0xc00096fec8)
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]:         /build/go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1125 +0x16cf
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]: github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).Sync(0xc000786210, 0x0, 0x0)
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]:         /build/go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:225 +0x238
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]: github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).Run(0xc000786210, 0xc0006c5800, 0xc0000a02a0, 0xc0006ca430)
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]:         /build/go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:142 +0x16e
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]: created by github.com/cloudnativelabs/kube-router/pkg/cmd.(*KubeRouter).Run
Jan 20 23:24:30 container-s03 vz10gxvq9smcbmm5m0kl5s88nsrw1qr0-unit-script-kube-router-start[29764]:         /build/go/src/github.com/cloudnativelabs/kube-router/pkg/cmd/kube-router.go:142 +0xf23
Jan 20 23:24:30 container-s03 systemd[1]: kube-router.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 20 23:24:30 container-s03 systemd[1]: kube-router.service: Failed with result 'exit-code'.
```

The problem is that kube-router assumes the presence of a port number, which isn't actually required to be present.

In other words, anybody with the permissions to create or modify network policies, can crash kube-router, rendering most of the k8s cluster useless.

**Comment by adamtulinius** [comment]
`port:  The port on the given protocol. This can either be a numerical or named port on a pod. If this field is not provided, this matches all port names and numbers.`

- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#networkpolicyport-v1-networking-k8s-io

**Comment by murali-reddy** [comment]
@adamtulinius thanks for your PR and reporting the issue. Surprised this issue has not surfaced so far.
