### ISSUE TITLE
"Index out of range" after creation of an ipip interface

### ISSUE THREAD

**Issue by jprukner** [cloudnativelabs/kube-router#656]
Hey, I've got into a trouble with ipip interface. When I create one:

```
root@master:~# ip link add name ipip0 type ipip external;
```
kube-router crashes and gets into CrashLoopBackOff. The crash occured after deployment/scaling.
```
I0205 18:40:34.383771       1 kube-router.go:207] Running /usr/local/bin/kube-router version v0.2.5, built on 2019-02-01T04:01:01+0000, go1.10.8
I0205 18:40:35.004243       1 network_policy_controller.go:141] Starting network policy controller
I0205 18:40:35.013056       1 network_routes_controller.go:982] Found annotaion `kube-router.io/bgp-local-addresses` on node object so BGP will listen on local IP's: 10.80.96.1
I0205 18:40:35.025587       1 network_services_controller.go:278] Starting network services controller
I0205 18:40:36.121371       1 network_routes_controller.go:222] Starting network route controller
I0205 18:40:36.126723       1 network_routes_controller.go:800] Could not find BGP peer password info in the node's annotations. Assuming no passwords.
time="2019-02-05T18:40:36Z" level=info msg="Add a peer configuration for:10.80.96.0" Topic=Peer
time="2019-02-05T18:40:51Z" level=info msg="Peer Up" Key=10.80.96.0 State=BGP_FSM_OPENCONFIRM Topic=Peer


 E0205 18:45:22.540155       1 runtime.go:66] Observed a panic: "index out of range" (runtime error: index out of range)
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/asm_amd64.s:573
/home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/panic.go:502
/home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/panic.go:28
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/vishvananda/netlink/link_linux.go:2137
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/vishvananda/netlink/link_linux.go:1354
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/vishvananda/netlink/link_linux.go:1458
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/vishvananda/netlink/link_linux.go:1438
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:2194
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:575
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:1158
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:733
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:2292
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:202
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:540
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/asm_amd64.s:2361
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 153 [running]:
github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x168db40, 0x2655e10)
	/home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/panic.go:502 +0x229
github.com/cloudnativelabs/kube-router/vendor/github.com/vishvananda/netlink.parseIptunData(0x1aa9760, 0xc42089aea0, 0xc420023c00, 0xd, 0x10)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/vishvananda/netlink/link_linux.go:2137 +0x2f9
github.com/cloudnativelabs/kube-router/vendor/github.com/vishvananda/netlink.LinkDeserialize(0x0, 0xc420725648, 0x300, 0x9b8, 0x1aa9aa0, 0xc4204868c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/vishvananda/netlink/link_linux.go:1354 +0xbeb
github.com/cloudnativelabs/kube-router/vendor/github.com/vishvananda/netlink.(*Handle).LinkList(0x266bbe0, 0x477665, 0x1740dc0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/vishvananda/netlink/link_linux.go:1458 +0x1df
github.com/cloudnativelabs/kube-router/vendor/github.com/vishvananda/netlink.LinkList(0x0, 0x1, 0x0, 0x0, 0x24)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/github.com/vishvananda/netlink/link_linux.go:1438 +0x2d
github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.getAllLocalIPs(0x166c9a0, 0xc4208a22a0, 0x19146d3, 0x15, 0xc42094eb18)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:2194 +0x34
github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*NetworkServicesController).syncIpvsFirewall(0xc4207e4000, 0xc420983ae0, 0xb)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:575 +0x80
github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*NetworkServicesController).syncIpvsServices(0xc4207e4000, 0xc420847110, 0xc420847170, 0x0, 0x0)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:1158 +0x4940
github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*NetworkServicesController).OnEndpointsUpdate(0xc4207e4000, 0x18dcb60, 0xc42089a5a0)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:733 +0x346
github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*NetworkServicesController).newEndpointsEventHandler.func2(0x18dcb60, 0xc42020db00, 0x18dcb60, 0xc42089a5a0)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:2292 +0x3e
github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(0xc4208653a0, 0xc4208653b0, 0xc4208653c0, 0x18dcb60, 0xc42020db00, 0x18dcb60, 0xc42089a5a0)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:202 +0x5d
github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc42062f810)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:540 +0x1b7
github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.(*processorListener).(github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.run)-fm()
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383 +0x2a
github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc4200140d0, 0xc420865490)
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

Result of `ip link`:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp0s20f0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether 0c:c4:7a:e5:46:d6 brd ff:ff:ff:ff:ff:ff
3: enp0s20f1: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc mq master bond0 state DOWN mode DEFAULT group default qlen 1000
    link/ether 0c:c4:7a:e5:46:d7 brd ff:ff:ff:ff:ff:ff
4: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 xdpgeneric qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 0c:c4:7a:e5:46:d6 brd ff:ff:ff:ff:ff:ff
    prog/xdp id 141 tag 0aa1937915f165e0 jited 
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:7d:25:dd:59 brd ff:ff:ff:ff:ff:ff
8: kube-dummy-if: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether d6:d1:1e:61:eb:ad brd ff:ff:ff:ff:ff:ff
9: kube-bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 0a:58:0a:50:60:41 brd ff:ff:ff:ff:ff:ff
11: veth8ff29ae9@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master kube-bridge state UP mode DEFAULT group default 
    link/ether 06:67:70:6f:ed:c3 brd ff:ff:ff:ff:ff:ff link-netnsid 1
12: veth632f2237@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master kube-bridge state UP mode DEFAULT group default 
    link/ether d2:d5:3b:97:e1:d9 brd ff:ff:ff:ff:ff:ff link-netnsid 2
13: vethddd6646f@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master kube-bridge state UP mode DEFAULT group default 
    link/ether a2:16:fe:0b:78:38 brd ff:ff:ff:ff:ff:ff link-netnsid 0
14: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
24: ipip0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
26: veth4a18cc15@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master kube-bridge state UP mode DEFAULT group default 
    link/ether 1a:2d:dd:98:58:e5 brd ff:ff:ff:ff:ff:ff link-netnsid 3
```
Server is running Ubuntu 18.04.

Crash seems to be occurring in github.com/vishvanda/netlink library. I am willing to do a PR. Any ideas on how to mitigate this issue? @murali-reddy

**Comment by jprukner** [comment]
I guess this would do it. Gonna test it.
github.com/vishvananda/netlink/link_linux.go:
```
func parseIptunData(link Link, data []syscall.NetlinkRouteAttr) {
	iptun := link.(*Iptun)
	for _, datum := range data {
		if len(datum.Value) > 0 {
			switch datum.Attr.Type {
			case nl.IFLA_IPTUN_LOCAL:
				iptun.Local = net.IP(datum.Value[0:4])
			case nl.IFLA_IPTUN_REMOTE:
				iptun.Remote = net.IP(datum.Value[0:4])
			case nl.IFLA_IPTUN_TTL:
				iptun.Ttl = uint8(datum.Value[0])
			case nl.IFLA_IPTUN_TOS:
				iptun.Tos = uint8(datum.Value[0])
			case nl.IFLA_IPTUN_PMTUDISC:
				iptun.PMtuDisc = uint8(datum.Value[0])
			case nl.IFLA_IPTUN_ENCAP_SPORT:
				iptun.EncapSport = ntohs(datum.Value[0:2])
			case nl.IFLA_IPTUN_ENCAP_DPORT:
				iptun.EncapDport = ntohs(datum.Value[0:2])
			case nl.IFLA_IPTUN_ENCAP_TYPE:
				iptun.EncapType = native.Uint16(datum.Value[0:2])
			case nl.IFLA_IPTUN_ENCAP_FLAGS:
				iptun.EncapFlags = native.Uint16(datum.Value[0:2])
			case nl.IFLA_IPTUN_COLLECT_METADATA:
				iptun.FlowBased = int8(datum.Value[0]) != 0
			}
		}
	}
}
```

**Comment by jprukner** [comment]
The if statement I mentioned in my last comment mitigates the issue. The question is whether it is an optimal solution or not.
