### ISSUE TITLE
Failed to create ipvs service for node port due to: file exists

### ISSUE THREAD

**Issue by dsx** [cloudnativelabs/kube-router#907]
Kube-router crashes after service update:

```+ '[' '!' -f /etc/cni/net.d/10-kuberouter.conflist ]
+ '[' -f /etc/cni/net.d/60-cri-o-bridge.conf ]
+ TMP=/etc/cni/net.d/.tmp-kuberouter-cfg
+ cp /etc/kube-router/cni-conf.json /etc/cni/net.d/.tmp-kuberouter-cfg
+ mv /etc/cni/net.d/.tmp-kuberouter-cfg /etc/cni/net.d/10-kuberouter.conflist
+ '[' '!' -f2020-05-22T18:11:07.840301169-04:00  /var/lib/kube-router/kubeconfig ]
stream closed
kube-router I0522 22:31:29.658859       1 kube-router.go:216] Running /usr/local/bin/kube-router version v1.0.0-rc4, built on 2020-05-20T19:03:51+0000, go1.10.8
kube-router I0522 22:31:30.378017       1 network_policy_controller.go:142] Starting network policy controller
kube-router I0522 22:31:30.378037       1 network_policy_controller.go:147] Starting network policy controller full sync goroutine
kube-router I0522 22:31:30.388679       1 network_routes_controller.go:981] Could not find annotation `kube-router.io/bgp-local-addresses` on node object so BGP will listen on node IP: 192.0.2.1 address.
kube-router time="2020-05-22T22:31:30Z" level=warning msg="Running modprobe ip_vs failed with message: `modprobe: can't change directory to '5.4.33': No such file or directory`, error: exit status 1"
kube-router I0522 22:31:30.401850       1 network_services_controller.go:287] Starting network services controller
kube-router E0522 22:31:30.473520       1 network_routes_controller.go:209] Failed to enable netfilter for bridge. Network policies and service proxy may not work: exit status 1
kube-router I0522 22:31:30.473577       1 network_routes_controller.go:225] Starting network route controller
kube-router I0522 22:31:30.482802       1 network_routes_controller.go:752] Could not find BGP peer info for the node in the node annotations so skipping configuring peer.
kube-router E0522 22:31:30.522678       1 service_endpoints_sync.go:201] Failed to create ipvs service for node port due to: file exists
kube-router panic: runtime error: invalid memory address or nil pointer dereference
kube-router [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf82aa7]
kube-router goroutine 170 [running:
kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.ipvsServiceString(0x0, 0xc42121af40, 0x1c)
kube-router     /go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:1447 +0x37
kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*linuxNetworking).ipvsAddServer(0xc42066f7e8, 0x0, 0xc42070d700, 0x152020-05-22T18:31:30.525022669-04:00 , 0xc420e4cf40)
kube-router     /go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:1717 +0x303
kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*NetworkServicesController).setupNodePortServices(0xc4203ec640, 0xc420e9e7b0, 0xc420e9e7e02020-05-22T18:31:30.525037649-04:00 , 0xc420947a28, 0x0, 0x0)
kube-router     /go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/service_endpoints_sync.go:230 +0x7dd
kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*NetworkServicesController).syncIpvsServices(0xc4203ec640, 0xc420e9e7b0, 0xc420e9e7e0, 0x0, 2020-05-22T18:31:30.525048805-04:00 0x0)
kube-router     /go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/service_endpoints_sync.go:43 +0x16f
kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*NetworkServicesController).doSync(0xc4203ec640, 0x0, 0x0)
kube-router     2020-05-22T18:31:30.525063764-04:00 /go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:439 +0x143
kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*NetworkServicesController).Run(0xc4203ec640, 0xc42018cf00, 0xc42016c960, 0xc420166ff0)
kube-router     /go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:357 +0x4012020-05-22T18:31:30.525078763-04:00 
kube-router created by github.com/cloudnativelabs/kube-router/pkg/cmd.(*KubeRouter).Run
kube-router     /go/src/github.com/cloudnativelabs/kube-router/pkg/cmd/kube-router.go:179 +0xa8c
kube-router stream closed
```

**Comment by aauren** [comment]
Looks like you're missing the ipvs module in your kernel

**Comment by murali-reddy** [comment]
> Kube-router crashes after service update:

@dsx did you mean after upgrading kube-router to latest version?

Looks like modprobe for both modules `br_netfilter` and `ip_vs` has failed. What manifest are you using to deploy kube-router. Is host path `/lib/modules` mounted in to the kube-router pod?

**Comment by dsx** [comment]
Modules are loaded into the kernel by other means, `/lib/modules` is mounted inside pod. Service proxy works just fine, except for sporadic crashes like this one. Tried `1.0.0-rc3` and `1.0.0-rc4`, both show this behavior.

**Comment by murali-reddy** [comment]
Basically `modprobe br_netfilter` and `modprobe -va ip_vs` comands failed to run in the container.  May be try running the commands  in side the kube-router pod and see if they run

**Comment by dsx** [comment]
Both do run successfully if I run it inside container. But like I mentioned, all required modules are loaded into the kernel by other means at system boot time, way before containers are started.
